package chapter_07;
/** 
 * 		(Count single digits) Write a program that generates 100 random integers between
 * 		0 and 9 and displays the count for each number. (Hint: Use an array of ten integers,
 * 		say counts, to store the counts for the number of 0s, 1s, . . . , 9s.) 
 * 		
 * @author lucasmaximo
 *
 */

/** Necessary imports */
import java.util.Random;

/** Creating the class named Exercise_7_07 */
public class Exercise_7_07{
	


	/** Creating the main method */
	public static void main(String[] arg) {
		
		/** Created the necessary objects */
		Random r = new Random();
		
		/** Created the necessary variables */
		int [] myArray = new int [10];
		int count = 0;
		int position = 0;
		
		/** Printed out the initial message information */
		System.out.print("\n\n\tThe numbers\t");
		
		/** Created a for loop in order to generate 100 random integers */
		for(int i = 1; i <= 100; i++) {
			//generate a new random number between 0 and 9 every new loop
			int number = r.nextInt(10);
			//summ the new random number 
			count+= number;
			System.out.print(number + " ");
			/** created an if statement in order to insert the summ of the ten random numbers 
			 * generated by the loop */
			if((i % 10 == 0) && (i != 0)){
				
				//inserting the summ into the positions of the array
				myArray[position] = count;
				System.out.print(" -> " + myArray[position] + "\n\t\t\t");
				position += 1;
				//initiating the cout
				count = 0;
			}//closing the if statement
			
		}//closing the for loop 
		
		/** Printed out the array generated */
		Exercise_7_05.printOutArray(myArray);
	}//closing the main method

	


}//closing the class_7_07
